[package]
name = "mangovillage_common"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
durian.workspace = true
bevy.workspace = true
serde.workspace = true